### ISSUE TITLE
SW-2: Using  chaos-operator to test binlog

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#33]
## Description
Now. Binlog chaos testing is on going. we should finish it. Add more tests in abtests
## Difficulty

- Hard

## Score

- 3000

## TODO list

- [ ] Make a helm chart that can start [short road](#short-road) tests (500 points / medium)
- [ ] Make a helm chart that can start [long road](#long-road) tests (500 points / medium)
- [ ] Support more nodes in [SQLSmith](#test-framework) (500 points / medium)
- [ ] Refine abtest framework and SQLSmith (1000 points / hard)
- [ ] Use test framework finding binlog bugs (500 points)

## Mentor(s)

- @you06 

## Recommended Skills

- k8s, chaos, binlog architect

## More information

<h3 id="short-road">Short Road</h3>

```
TiDB -> pump -> drainer -> TiDB/MySQL
```

<h3 id="long-road">Long Road</h3>

```
TiDB -> pump -> drainer -> Kafka -> arbiter -> TiDB/MySQL
```

<h3 id="test-framework">SQLSmith</h3>

There are some urgent-need nodes in SQLSmith.

- [x] Alter table statement (add/delete index/column)

- [ ] Delete table statement
