### ISSUE TITLE
SW-3: Using  chaos-operator to test cdc

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#34]
## Description
cdc now did not have chaos test. we should add it
## Difficulty

- Hard

## Score

- 4500

## Mentor(s)

- @overvenus 
- @amyangfei 

## Recommended Skills

- k8s, chaos,cdc architect

##  TODOs

- [x] run cdc in kubernetes 
- [x] develop a workload case 
- [x] develop  a check case ( can be merged with task 2 )
- [ ] inject chaos tikv and to check cdc ( pod kill / pod failure / network delay / network partation / io delay ) 
- [ ] inject chaos to cdc 
- [ ] inject chaos both cdc and tikv 
- [ ] last but not least, output a test report to record issue and test result
